Fix InspectStringMultipleRulesTests to use large enough string to det…
GoogleCloudPlatform/dotnet-docs-samples pull request #1166
Opened 2020-08-26 21:54 UTC by pheonixblade9

…ect properly

2020-08-27 13:50 UTC, amanda-tarafa requested changes
A minor change, thanks for fixing so quickly!

2020-08-27 13:50 UTC, amanda-tarafa commented on dlp/api/Snippets/README.md
>  # .NET Cloud Translation API Samples
```suggestion
# .NET Cloud DLP API Samples
```

2020-08-27 13:50 UTC, amanda-tarafa commented on dlp/api/Snippets.Tests/InspectStringMultipleRulesTests.cs
> -        [Fact(Skip = "https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/1159")]
You need to leave in [Fact] so that it's ran as a test.

2020-08-27 18:05 UTC, pheonixblade9 commented
Please go ahead and merge this if it looks good.

2020-09-01 10:15 UTC, amanda-tarafa approved these changes
LGTM

2020-09-01 10:17 UTC, merged