chore: re-enable disabled test since quotas already increased
GoogleCloudPlatform/dotnet-docs-samples pull request #1259
Opened 2021-02-11 20:12 UTC by munkhuushmgl

Fixes #947

2021-02-12 10:49 UTC, amanda-tarafa commented
They failed presubmit on Windows, I think because of the dependencies are old. Can you update the dependecies of the samples to netstandard2.1 and of the tests to netcoreapp3.1 and make sure that the libraries are the newest?

2021-02-12 18:18 UTC, munkhuushmgl commented
> They failed presubmit on Windows, I think because of the dependencies are old. Can you update the dependecies of the samples to netstandard2.1 and of the tests to netcoreapp3.1 and make sure that the libraries are the newest?

Ok will do

2021-02-12 19:09 UTC, munkhuushmgl commented
@amanda-tarafa PTaL looks like something outside of my changes failing

2021-02-16 11:25 UTC, amanda-tarafa requested changes
Just a minor detail.
Otherwise seems to have passed. Once merged I'll keep a close eye on it and see if we reach quota again.

2021-02-16 11:25 UTC, amanda-tarafa commented on dialogflow/api/Test/DialogflowSampleTests.csproj
> +    <PackageReference Include="Google.Cloud.Dialogflow.V2" Version="3.1.0" />
Remove this package reference. You already get it when you reference the sample project.

2021-02-17 15:30 UTC, amanda-tarafa approved these changes
LGTM. Will merge after running tests again.

2021-02-17 16:24 UTC, merged