chore: removing unsupported samples
GoogleCloudPlatform/dotnet-docs-samples pull request #1283
Opened 2021-03-18 22:08 UTC by munkhuushmgl

go/cloud-ai-2021-snippet-cleanup

2021-03-19 09:11 UTC, amanda-tarafa commented
Info on non-vision failures:
- Storage failure: #1272 
- Spanner, transient failure. We are retrying but in this case it wasn't enough. This should fall within normal expeced behaviour.
- Asset failure: #1278

2021-03-19 09:14 UTC, amanda-tarafa requested changes
There's one tag reported by snippet-bot as being deleted but used in docs.
And also Vision tests seem to be failing, most of them.

2021-03-19 22:22 UTC, munkhuushmgl commented
> There's one tag reported by snippet-bot as being deleted but used in docs.
> And also Vision tests seem to be failing, most of them.

one region tag should be fixed by now.

cl/363982019

2021-03-22 12:22 UTC, amanda-tarafa commented
Region tags look good.
Vision tests consistently failing though. See [here](https://source.cloud.google.com/results/invocations/aa056682-b048-4bb8-8695-3ade0d4ca275/targets/github%2Fdotnet-docs-samples%2Fvision%2Fapi%2FVisionTest%2FTestResults/tests) for instance.

2021-03-22 17:38 UTC, munkhuushmgl commented
> Region tags look good.
> Vision tests consistently failing though. See [here](https://source.cloud.google.com/results/invocations/aa056682-b048-4bb8-8695-3ade0d4ca275/targets/github%2Fdotnet-docs-samples%2Fvision%2Fapi%2FVisionTest%2FTestResults/tests) for instance.

Looks like I did not delete tests related to removed samples.

2021-03-23 12:05 UTC, amanda-tarafa commented
Still lots of [failures](https://source.cloud.google.com/results/invocations/43ce07a1-f06c-4695-b065-acc02453e7ab/targets/github%2Fdotnet-docs-samples%2Fvision%2Fapi%2FVisionTest%2FTestResults/tests) for Vision tests. Some files seem to be missing.

2021-03-23 17:15 UTC, munkhuushmgl commented
@amanda-tarafa Should be good now.

2021-03-24 12:14 UTC, amanda-tarafa requested changes

2021-03-24 12:14 UTC, amanda-tarafa commented on vision/api/VisionTest/VisionTest.cs
> -namespace GoogleCloudSamples
We need to keep the tests for the two samples remaining.

2021-03-24 12:21 UTC, amanda-tarafa commented
F# failure is related to this PR, see #1289. I'll fix it.

2021-03-24 17:25 UTC, munkhuushmgl commented
> F# failure is related to this PR, see #1289. I'll fix it.

how do I see test failures related to vision?

2021-03-24 18:10 UTC, amanda-tarafa commented
I already fixed #1289 so no worries about it.

Vision runs in Kokoro CI Windows 3 and Kokoro CI Linux 3. You can click on `Details` link of those machines (on the widget at the end of the PR that shows checks passing and failing). And there you can click on the Vision related link.

2021-04-14 20:09 UTC, munkhuushmgl commented
@amanda-tarafa PTAL something failed outside of my changes

2021-04-16 10:12 UTC, amanda-tarafa commented
Failures are unrelated and being tracked:

* SQL Server: #1311

2021-04-16 10:13 UTC, amanda-tarafa approved these changes
LGTM

2021-04-16 10:14 UTC, merged