docs(iam-samples): extract PrivateKeyData from ServiceAccountKey
GoogleCloudPlatform/dotnet-docs-samples pull request #1610
Opened 2022-01-28 09:55 UTC by Sita04

For more context: b/216208252

Fix: Extracting the PrivateKeyData which contains the json key credential in base64 format.

2022-01-28 11:13 UTC, Sita04 commented
fix(iam-samples): convert base64 encoded PrivateKeyData to String

2022-01-28 11:48 UTC, amanda-tarafa requested changes
A suggestion but otherwise looks good.

2022-01-28 11:48 UTC, amanda-tarafa commented on iam/api/ServiceAccountKeys/ServiceAccountKeysCreate.cs
> +        jsonKeyFile = Encoding.UTF8.GetString(valueBytes);
It's better if we are explicit in samples, and I think the jsonKeyFile variable is not declared.

```suggestion
        byte[] valueBytes = System.Convert.FromBase64String(key.PrivateKeyData);
        string jsonKeyContent = Encoding.UTF8.GetString(valueBytes);
```

2022-01-28 16:28 UTC, amanda-tarafa requested changes

2022-01-28 16:28 UTC, amanda-tarafa commented on iam/api/ServiceAccountKeys/ServiceAccountKeysCreate.cs
> +        string jsonKeyContent = Encoding.UTF8.GetString(valueBytes);
This is not building because you are missing an import statent at the top of the file (alphabetically):

```
using System.Text;
```

2022-01-31 11:15 UTC, amanda-tarafa approved these changes
LGTM, thanks!

2022-01-31 11:16 UTC, merged