Cross region backup
GoogleCloudPlatform/dotnet-docs-samples pull request #1663
Opened 2022-03-23 07:11 UTC by anshuldavid13

WIP - Created to add the cross region backup changes done as a stage sample using protos.

2022-03-24 17:24 UTC, amanda-tarafa requested changes

2022-03-24 17:24 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples/CopyBackup.cs
> +    public void CopyBackup(string sourceInstanceId, string sourceProjectId, string sourceBackupId, string targetInstanceId, string targetProjectId, string targetBackupId, DateTimeOffset expireTime, D
```suggestion
    public void CopyBackup(
        string sourceInstanceId, string sourceProjectId, string sourceBackupId,
        string targetInstanceId, string targetProjectId, string targetBackupId,
        DateTimeOffset expireTime)
```

2022-03-24 17:24 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples/CopyBackup.cs
> +        DatabaseAdminClient databaseAdminClient = new DatabaseAdminClientBuilder { Endpoint = "staging-wrenchworks.sandbox.googleapis.com" }.Build();
Do we still need to use the sandbox endpoint or is this feature available already?

2022-03-24 17:24 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples/CopyBackup.cs
> +            Parent = "projects/" + targetProjectId + "/instances/" + targetInstanceId,
There should be a property named something like ParentAsInstanceName or similar that you could use here.

2022-03-24 17:24 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples/CopyBackup.cs
> +            ExpireTime = (expireTime <= maxExpireTime) ? Timestamp.FromDateTimeOffset(expireTime) : Timestamp.FromDateTimeOffset(maxExpireTime)
I don't think this is necessary here.
Receive just one parameter and use that one to set the ExpireTime.

2022-03-24 17:24 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples/CopyBackup.cs
> +        Console.WriteLine($"Backup {backup.Name} of size {backup.SizeBytes} bytes was created at {backup.CreateTime} from {backup.Database} and is in state {backup.State} and has version time {backup
```suggestion
        Backup backup = completedResponse.Result;

        Console.WriteLine($"Backup created successfully.");
        Console.WriteLine($"Backup with Id {sourceBackupId} has been copied from {sourceProjectId}/{sourceInstanceId} to {targetProjectId}/{targetInstanceId} Backup {targetBackupId}");
        Console.WriteLine($"Backup {backup.Name} of size {backup.SizeBytes} bytes was created at {backup.CreateTime} from {backup.Database} and is in state {backup.State} and has version time {backup.VersionTime.ToDateTime()}");
        
        return backup;
```

2022-03-24 17:24 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples.Tests/CopyBackupTest.cs
> +        DatabaseAdminClient databaseAdminClient = new DatabaseAdminClientBuilder { Endpoint = "staging-wrenchworks.sandbox.googleapis.com" }.Build();
```suggestion
```

2022-03-24 17:24 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples.Tests/CopyBackupTest.cs
> +        DateTimeOffset maxExpireTime = DateTimeOffset.Now.AddDays(10);
```suggestion
```

2022-03-24 17:24 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples.Tests/CopyBackupTest.cs
> +        copyBackupSample.CopyBackup(source_Instance_id, source_Project_id, source_backupId, target_Instance_id, target_Project_id, target_backupId, expireTime, maxExpireTime);
```suggestion
        var backup = copyBackupSample.CopyBackup(source_Instance_id, source_Project_id, source_backupId, target_Instance_id, target_Project_id, target_backupId, expireTime);
```

2022-03-24 17:24 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples.Tests/CopyBackupTest.cs
> +        string target_Instance_id = "testinst1";
These won't work, I propose we use the same porject id and instance id as source, we just copy the backup to a new place.

2022-03-24 17:24 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples.Tests/CopyBackupTest.cs
> +        Backup backup = databaseAdminClient.GetBackup(backupName);
```suggestion
```

2022-03-24 17:24 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples.Tests/CopyBackupTest.cs
> +        string target_backupId = "backup_target6";
You'll need to generate a random ID here, else all tests will clash with each other.

2022-04-04 09:27 UTC, amanda-tarafa requested changes

2022-04-04 09:27 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples.Tests/CopyBackupTest.cs
> +        DateTimeOffset maxExpireTime = DateTimeOffset.Now.AddDays(10);
Let's leave this open until we have solved the issue around using two dates.

2022-04-04 09:27 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples.Tests/CopyBackupTest.cs
> +        DateTimeOffset maxExpireTime = DateTimeOffset.Now.AddDays(10);
Also, regardless of anything else, just put a few hours as expiry time, so that backups get deleted quickly.

2022-04-05 07:11 UTC, anshuldavid13 commented on spanner/api/Spanner.Samples/Spanner.Samples.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
Reverted

2022-04-05 09:42 UTC, amanda-tarafa approved these changes
I'm applying the suggestions myself to start running tests.

2022-04-05 09:42 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples/Spanner.Samples.csproj
> +﻿<Project Sdk="Microsoft.NET.Sdk">
There's still a change here, I'll try to revert it myself.
```suggestion
<Project Sdk="Microsoft.NET.Sdk">
```

2022-04-05 09:42 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples.Tests/CopyBackupTest.cs
> +        DateTimeOffset expireTime = DateTimeOffset.UtcNow.AddDays(7);
So that the backup is deleted quickly
```suggestion
        DateTimeOffset expireTime = DateTimeOffset.UtcNow.AddHours(12);
```

2022-04-05 09:42 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples.Tests/CopyBackupTest.cs
> +        string target_backupId = "test_"+Guid.NewGuid().ToString().Substring(0,16);
```suggestion
        string target_backupId = "test_" + Guid.NewGuid().ToString("N").Substring(0,16);
```

2022-04-05 12:13 UTC, amanda-tarafa commented
Errors are unrelated. Just Spanner quota being reached because we are executing several CI runs at the same time.
Force merging...

2022-04-05 12:14 UTC, merged