Pub-Sub Auth Push sample
GoogleCloudPlatform/dotnet-docs-samples pull request #1681
Opened 2022-04-07 08:00 UTC by hemanshv

Added pub-sub auth push [sample]([url](https://github.com/GoogleCloudPlatform/dotnet-docs-samples/issues/1234))
Please review

2022-04-13 11:30 UTC, amanda-tarafa requested changes
I think you probably need to modify the kestrel tests to test this new method. There's a *.json with the config, but I'm not very familiar with it. Let m know if you need help with that.

@anguillanneuf I'll request your review mostly to discuss a little about caching the tokens. I'll also leave a note on the internal emails.

2022-05-12 11:15 UTC, hemanshv commented
Addressed the review comments pls review

2022-05-12 12:51 UTC, amanda-tarafa commented
This will most likely need to wait till I'm back. But also, the tests are failing.

2022-05-13 06:15 UTC, hemanshv commented
@amanda-tarafa The local tests are resolved Please review once your are back, Thanks

2022-06-01 10:41 UTC, hemanshv commented
@amanda-tarafa  Please review

2022-06-07 09:08 UTC, amanda-tarafa approved these changes
LGTM with 3 tiny nits!

Thanks!

2022-06-07 09:08 UTC, amanda-tarafa commented on appengine/flexible/Pubsub/Controllers/HomeController.cs
> +            //   - Ensure that `payload.email` is equal to the expected service
```suggestion
            //   - Ensure that `payload.Email` is equal to the expected service

```

2022-06-07 10:21 UTC, amanda-tarafa commented
Thanks! I'll merge on green.

2022-06-07 10:43 UTC, merged