fix(appengine): Small fixes re: recent .NET 6 upgrades
GoogleCloudPlatform/dotnet-docs-samples pull request #2181
Opened 2023-05-09 18:11 UTC by jahjahbin

Fixes:
- WebSocket project added to solution was missing some config
- HelloWorld was missing launch settings -- this is an issue since the docs refer to port 5000 which is controlled by the launch settings, so docs are wrong now

2023-05-09 18:12 UTC, jinglundong approved these changes

2023-05-12 22:47 UTC, amanda-tarafa requested changes
There are conflicts now with the solution file. Otherwise, looks good.

2023-05-12 23:20 UTC, jahjahbin commented
> There are conflicts now with the solution file. Otherwise, looks good.

Done.

2023-05-13 01:24 UTC, jinglundong approved these changes

2023-05-14 22:02 UTC, amanda-tarafa approved these changes

2023-05-14 22:02 UTC, merged