feat: Adds samples for foreign key on delete cascade action.
GoogleCloudPlatform/dotnet-docs-samples pull request #2230
Opened 2023-06-13 09:15 UTC by anuragsrivstv

2023-06-13 09:20 UTC, anuragsrivstv commented
Currently samples are tested in the staging environment. Will test it again once the feature is available and sample integration tests are successful with it.  Keeping this PR as draft till then.

2023-07-20 12:21 UTC, anuragsrivstv commented
> Currently samples are tested in the staging environment. Will test it again once the feature is available and sample integration tests are successful with it. Keeping this PR as draft till then.

Now this PR can be reviewed.

2023-08-02 05:09 UTC, amanda-tarafa requested changes
A few suggestions that I think will improve tests.

2023-08-02 05:09 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples.Tests/CreateTableWithForeignKeyDeleteCascadeAsyncTest.cs
> +        var command = connection.CreateSelectCommand("SELECT table_name FROM information_schema.tables WHERE table_schema='public' OR table_schema=''");
```suggestion
        var command = connection.CreateSelectCommand("SELECT Count(*) FROM information_schema.tables WHERE table_name='Customers' OR table_name='ShoppingCarts'");
```

2023-08-02 05:09 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples.Tests/CreateTableWithForeignKeyDeleteCascadeAsyncTest.cs
> +        return tableNames;
```suggestion
        var tableCount = await command.ExecuteScalarAsync();
        Assert.Equals(2, tableCount);
```

2023-08-02 05:09 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples.Tests/CreateTableWithForeignKeyDeleteCascadeAsyncTest.cs
> +    private async Task<List<string>> ListTableNamesAsync(string projectId, string instanceId, string databaseId)
```suggestion
    private async Task AssertTablesCreatedAsync(string projectId, string instanceId, string databaseId)
```

2023-08-02 05:09 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples.Tests/CreateTableWithForeignKeyDeleteCascadeAsyncTest.cs
> +            Assert.Contains("ShoppingCarts", tables);
```suggestion
            await AssertTablesCreatedAsync(_spannerFixture.ProjectId, _spannerFixture.InstanceId, databaseId);
```

2023-08-02 05:09 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples.Tests/AlterTableWithForeignKeyDeleteCascadeAsyncTest.cs
> +    private async Task<List<string>> ListDeleteRuleConstraintsAsync(string projectId, string instanceId, string databaseId)
Change this one similar to the others.

2023-08-02 05:09 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples.Tests/AlterTableWithForeignKeyDeleteCascadeAsyncTest.cs
> +        using var connection = new SpannerConnection(connectionString);
Reuse the connection from the table creation. You can create the connection on the main method and pass it as a parameter to both helper methods.

2023-08-04 21:54 UTC, amanda-tarafa approved these changes
Thanks!

2023-08-04 21:54 UTC, merged