chore: Using Temp DB for Delete Sample Tests
GoogleCloudPlatform/dotnet-docs-samples pull request #2266
Opened 2023-07-05 06:44 UTC by anuragsrivstv

Parent Issue #2093

-  This is 1st PR containing changes to use temporary databases for all sample tests that modify the database. 

- This PR contains All Delete Sample Tests that needs to be updated.

- Number of affected tests files 3 out of 21 in #2216

2023-07-06 08:22 UTC, anuragsrivstv commented
Hi @amanda-tarafa , Can you please have a look at this PR. Thanks !

2023-07-06 08:23 UTC, amanda-tarafa commented
Yes, we'll do as soon as I get a chance, thanks!

2023-07-10 14:20 UTC, amanda-tarafa requested changes

2023-07-10 14:20 UTC, amanda-tarafa commented on spanner/api/Spanner.Samples.Tests/DeleteUsingPartitionedDmlCoreAsyncTest.cs
> +            Assert.True(rowCount >= 1);
I think that now we probably know exactly how many rows were deleted.

2023-07-12 11:33 UTC, anuragsrivstv commented on spanner/api/Spanner.Samples.Tests/DeleteUsingDmlCoreAsyncTest.cs
> +            await _spannerFixture.CreateSingersTableAndInsertDataAsync(databaseId);
Yes, in SpannerFixture.InitializeDatabaseAsync()

2023-07-12 12:04 UTC, anuragsrivstv commented on spanner/api/Spanner.Samples.Tests/DeleteUsingDmlReturningAsyncPostgresTest.cs
> +            await InsertDataAsync(databaseId);
>The version of RunWithTemporaryDatabaseAsync for non-postgress Database has some overloads that take extra statements, can we do similarly for Postgress, mainly for uniformity sake.
There cannot be Extra DDL statements while creating PostgreSQL.

>And also, there are some methods in the fixture called CreateSingersTableAndInsertData etc. Couldn't we just use the same methods everywhere? Why do we need this particular row to test that delete works?
CreateSingersTableAndInsertData Create the singers table and its containes DDL statement in Google Standard SQL format. Therefor we can not use the same function for Postgres. Also I believe going forward it's better to insert data there itself for tests using Temp DB as that way tests can be completely independent.

2023-07-14 12:39 UTC, anuragsrivstv commented
Tests are failing right now, will fix it.

2023-08-11 05:26 UTC, anuragsrivstv commented
Please do not review it right  now. Spanner fixture files has some conflicts. Resolving it.

2023-09-19 07:14 UTC, anuragsrivstv commented
Closing this PR as it's outdated. Will raise another one instead of it.

2023-09-19 07:14 UTC, closed without merging