docs(aiplatform): Add PredictTextClassificationSample #2396
GoogleCloudPlatform/dotnet-docs-samples pull request #2407
Opened 2023-11-10 11:58 UTC by meteatamel

2023-11-15 09:12 UTC, meteatamel commented
@hemanshv I think you missed to review this one?

2023-11-20 09:34 UTC, hemanshv requested changes

2023-11-20 09:48 UTC, meteatamel commented on aiplatform/api/AIPlatform.Samples.Tests/PredictTextClassificationTest.cs
> +    public void Runs()
Ack

2023-11-20 09:55 UTC, meteatamel commented on aiplatform/api/AIPlatform.Samples/PredictTextClassificationSample.cs
> +using wkt = Google.Protobuf.WellKnownTypes;
There's another `Value` in `Google.Cloud.AIPlatform.V1`, that's why we need to refer to the right one but `using Value = Google.Protobuf.WellKnownTypes.Value;` would be a better way of referring.

2023-11-20 09:56 UTC, meteatamel commented on aiplatform/api/AIPlatform.Samples/PredictTextClassificationSample.cs
> +- business
You mean align `-business` and the rest of the text with line 45? That'd introduce extra spaces in the string though, right? This is a multi-line string.

2023-11-20 09:56 UTC, meteatamel commented on aiplatform/api/AIPlatform.Samples/PredictTextClassificationSample.cs
> +                    ["content"] = wkt::Value.ForString(content),
It's an open question whether we should link to docs from these samples. These samples will be embedded in the docs, so I don't think it's needed but we'll let Amanda decide.

2023-11-20 09:57 UTC, meteatamel commented on aiplatform/api/AIPlatform.Samples/PredictTextClassificationSample.cs
> +        var responseContent = response.Predictions[0].StructValue.Fields["content"].StringValue;
Ack

2023-11-21 00:52 UTC, amanda-tarafa commented on aiplatform/api/AIPlatform.Samples.Tests/PredictTextClassificationTest.cs
> +    public void Runs()
Yes please, thatnks! Here, and elsewhere.

2023-11-21 00:52 UTC, amanda-tarafa commented on aiplatform/api/AIPlatform.Samples/PredictTextClassificationSample.cs
> +- business
Yes, we don't want to align these, as it's a multiline string, those spaces would show up on the string value itself.

2023-11-21 00:52 UTC, amanda-tarafa commented on aiplatform/api/AIPlatform.Samples/PredictTextClassificationSample.cs
> +using wkt = Google.Protobuf.WellKnownTypes;
As in other PRs, using an alias would be best.

2023-11-21 00:52 UTC, amanda-tarafa commented on aiplatform/api/AIPlatform.Samples/PredictTextClassificationSample.cs
> +                    ["content"] = wkt::Value.ForString(content),
If these are all explained in the docs where the samples are, then that's enough.

2023-11-21 00:52 UTC, amanda-tarafa commented on aiplatform/api/AIPlatform.Samples/PredictTextClassificationSample.cs
> +        var responseContent = response.Predictions[0].StructValue.Fields["content"].StringValue;
Yes, maybe. Specially @meteatamel if you are following my suggestion elsewhere to show sorted predictions based on score, then using linq might be cleaner.

2023-11-21 06:59 UTC, hemanshv commented on aiplatform/api/AIPlatform.Samples.Tests/PredictTextClassificationTest.cs
> +/*
placeholder to undo request changes

2023-11-21 15:29 UTC, meteatamel commented on aiplatform/api/AIPlatform.Samples/PredictTextClassificationSample.cs
> +        var responseContent = response.Predictions[0].StructValue.Fields["content"].StringValue;
I use Linq to get first but there's no score or anything like that really

2023-11-21 19:29 UTC, meteatamel commented
@hemanshv Let me know if anything else is needed here.

2023-11-21 19:59 UTC, merged