Add secrets team to codeowners
GoogleCloudPlatform/dotnet-docs-samples pull request #2856
Opened 2024-12-03 14:16 UTC by YashSaraf11

### Changes
* Add secrets manager team to the `secretmanager/` code-owners in _CODEOWNERS_ file

### Description
* Need access to the secrets-manager team to be able to review and partake in the review process.

2024-12-03 17:56 UTC, amanda-tarafa requested changes
Can you add your team also on the blunderbuss config here: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/main/.github/blunderbuss.yml. This is for automatic assignment of issues and PRs. Let me know if you have questions about that.

2024-12-04 09:03 UTC, YashSaraf11 commented on .github/blunderbuss.yml
> -  to:
This is an auto-change, as there was an unwanted whitespace, which got included as part of this change.

2024-12-04 09:07 UTC, YashSaraf11 commented
> Can you add your team also on the blunderbuss config here: https://github.com/GoogleCloudPlatform/dotnet-docs-samples/blob/main/.github/blunderbuss.yml. This is for automatic assignment of issues and PRs. Let me know if you have questions about that.

Sure, have included this change as well.

2024-12-09 18:31 UTC, amanda-tarafa approved these changes

2024-12-09 18:32 UTC, merged