chore: Add SecretManager service regional code samples
GoogleCloudPlatform/dotnet-docs-samples pull request #2880
Opened 2024-12-23 09:28 UTC by YashSaraf11

### Changes
* Added code samples for regional APIs.
* Added test files for the regional code samples added.
* Added `RegionalSecretManagerFixture.cs` file for testing the regional code samples added.

2024-12-26 05:38 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples.Tests/AccessRegionalSecretVersionTests.cs
> + * Copyright 2020 Google LLC
Update copyright year

2024-12-26 05:38 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples.Tests/AddRegionalSecretVersionTests.cs
> + * Copyright 2020 Google LLC
Update copyright year

2024-12-26 05:38 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples.Tests/CreateRegionalSecretTests.cs
> + * Copyright 2020 Google LLC
Update copyright year in all the files

2024-12-26 06:08 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples/EnableRegionalSecretVersion.cs
> +        SecretVersionName secretVersionName = SecretVersionName.FromProjectLocationSecretSecretVersion(projectId, locationId, secretId, secretVersionId);
Avoid lengthy lines, break them down, it increases readability.

2024-12-26 06:14 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples.Tests/DeleteRegionalSecretWithEtagTests.cs
> +        _sample.DeleteRegionalSecretWithEtag(projectId: secretName.ProjectId, locationId: secretName.LocationId, secretId: secretName.SecretId, etag: updatedEtag);
Break down such lines into smaller ones to increase readability

2024-12-26 06:19 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples.Tests/DisableRegionalSecretVersionWithEtagTests.cs
> +        // Create the Secret Manager Client with the regional endpoint.
Update this comment to 
"Create the Regional Secret Manager Client"
Apply this everywhere.

2024-12-26 08:24 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples.Tests/ListRegionalSecretVersionsWithFilterTests.cs
> +    }
Please add some assert statements

2024-12-26 08:25 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples.Tests/ListRegionalSecretsTests.cs
> +    }
Please add some assert statements

2024-12-26 08:25 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples.Tests/ListRegionalSecretsWithFilterTests.cs
> +    }
Please add some assert statements in all the tests

2024-12-26 08:26 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples.Tests/RegionalSecretManagerFixture.cs
> +        Console.WriteLine("Hello World!");
Remove unnecessary print statements

2024-12-26 08:27 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples.Tests/RegionalSecretManagerFixture.cs
> +        LocationId = Environment.GetEnvironmentVariable("GOOGLE_CLOUD_LOCATION") ?? "us-west1";
Please make sure both the locations are same

2024-12-26 09:56 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples.Tests/RegionalSecretManagerFixture.cs
> +        SecretForQuickstartName = SecretName.FromProjectLocationSecret(ProjectId, LocationId, RandomId());
Will this secret be eventually cleaned up as well?

2024-12-26 09:59 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples.Tests/RegionalSecretManagerFixture.cs
> +        }
Add some log here

2024-12-26 10:08 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples/UpdateRegionalSecretWithAlias.cs
> +            VersionAliases = { ["test"] = 1 }
What does this signify, add a comment here, and why is this hardcoded?

2024-12-26 10:08 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples.Tests/UpdateRegionalSecretWithAliasTests.cs
> +        Assert.Equal(1, result.VersionAliases["test"]);
What does this signify?

2024-12-26 10:15 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples.Tests/UpdateRegionalSecretWithEtagTests.cs
> +        string updatedEtag = secret.Etag;
Why the updated etag same as original etag?

2024-12-26 10:37 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples/ListRegionalSecretVersions.cs
> +            // ...
Please complete this

2024-12-26 10:37 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples/ListRegionalSecretVersionsWithFilter.cs
> +            // ...
Please complete this

2024-12-26 10:38 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples/ListRegionalSecrets.cs
> +            // ...
Please complete this

2024-12-26 10:38 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples/ListRegionalSecretsWithFilter.cs
> +            // ...
Please complete this

2024-12-26 10:38 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples/RegionalQuickstart.cs
> +        //
Why this extra line?

2024-12-26 10:39 UTC, vipul7499 commented on secretmanager/api/SecretManager.Samples/UpdateRegionalSecretWithAlias.cs
> +            VersionAliases = { ["test"] = 1 }
What does this signifiy?

2025-01-03 04:27 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/AccessRegionalSecretVersionTests.cs
> + * Copyright 2020 Google LLC
Sure. I have updated everything to 2024, as per the file creation year.

2025-01-03 04:27 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/AddRegionalSecretVersionTests.cs
> + * Copyright 2020 Google LLC
Sure. I have updated everything to 2024, as per the file creation year.

2025-01-03 04:29 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/CreateRegionalSecretTests.cs
> + * Copyright 2020 Google LLC
Sure. I have updated everything to 2024, as per the file creation year.

2025-01-03 04:30 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples/EnableRegionalSecretVersion.cs
> +        SecretVersionName secretVersionName = SecretVersionName.FromProjectLocationSecretSecretVersion(projectId, locationId, secretId, secretVersionId);
I have used the `dotnet format` and the breakup was automatically adjusted as per the formatting rules set. I will try to change the formatting rules if possible or manual break the lines.

2025-01-03 04:30 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/DeleteRegionalSecretWithEtagTests.cs
> +        _sample.DeleteRegionalSecretWithEtag(projectId: secretName.ProjectId, locationId: secretName.LocationId, secretId: secretName.SecretId, etag: updatedEtag);
I have used the `dotnet format` and the breakup was automatically adjusted as per the formatting rules set. I will try to change the formatting rules if possible or manual break the lines.

2025-01-03 04:30 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/DisableRegionalSecretVersionWithEtagTests.cs
> +        // Create the Secret Manager Client with the regional endpoint.
Sure, have made this change everywhere possible.

2025-01-03 04:31 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/RegionalSecretManagerFixture.cs
> +        SecretForQuickstartName = SecretName.FromProjectLocationSecret(ProjectId, LocationId, RandomId());
I had missed deleting one of them, have fixed this now to delete and cleanup all of them.

2025-01-03 04:31 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples/RegionalQuickstart.cs
> +        //
Have removed this extra line.

2025-01-03 04:35 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/UpdateRegionalSecretWithEtagTests.cs
> +        string updatedEtag = secret.Etag;
Its an mistake on the variable name, I will update it to etag for clearing the misconception. Thanks for pointing it out.

2025-01-03 04:35 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/RegionalSecretManagerFixture.cs
> +        LocationId = Environment.GetEnvironmentVariable("GOOGLE_CLOUD_LOCATION") ?? "us-west1";
Sure, that was just an example, will update all to `us-west1`.

2025-01-03 04:36 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/RegionalSecretManagerFixture.cs
> +        Console.WriteLine("Hello World!");
Have removed this code line, thanks.

2025-01-07 05:34 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/ListRegionalSecretVersionsTests.cs
> +    }
Have added assert statements here as per the request.

2025-01-07 05:34 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/ListRegionalSecretsTests.cs
> +    }
Have added assert statements here as per the request.

2025-01-07 05:34 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/ListRegionalSecretsWithFilterTests.cs
> +    }
Have added assert statements here as per the request.

2025-01-07 05:35 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples/UpdateRegionalSecretWithAlias.cs
> +            VersionAliases = { ["test"] = 1 }
Have added comments to signify the detail, and this hardcoded just as an example of adding alias to the secret version.

2025-01-07 05:36 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples/ListRegionalSecretVersionsWithFilter.cs
> +            // ...
Have added console statements here as per the request.

2025-01-07 05:36 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples/ListRegionalSecretsWithFilter.cs
> +            // ...
Have added assert statements here as per the request.

2025-01-07 05:37 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/UpdateRegionalSecretWithAliasTests.cs
> +        Assert.Equal(1, result.VersionAliases["test"]);
This is for the test, that the secret version "1" should have alias of "test".

2025-01-07 05:37 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples/ListRegionalSecretVersions.cs
> +            // ...
Have added print statements here as per the request.

2025-01-07 05:37 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples/ListRegionalSecrets.cs
> +            // ...
Have added print statements here as per the request.

2025-01-07 05:38 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/ListRegionalSecretVersionsWithFilterTests.cs
> +    }
Have added assert statements here as per the request.

2025-01-07 05:53 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/RegionalSecretManagerFixture.cs
> +        }
Have added an error console message to be printed.

2025-01-28 19:27 UTC, amanda-tarafa requested changes
Please rebase this PR on main as at the moment your branch is outdated and this PR is including unrelated Secret Manager changes.

There are several comments that although left in one or two files only, should be addressed everywhere.

I aslo have some concerns about:

- assumptions that tests run in a given order
- assumptions that tests do not run in parallel
- reuse of fxiture resources in tests that modify said resources

All of these may be addressed by creating specific resources for each of the tests that modify the resources. And ideally those should be set up and deleted on each of the tests using the fixture methods as helpers. Shares resources in the fixture should only be used for tests that do not modify those resources. I know some of this was inspired by the existing global samples, but, although those are not perfect, there are way less of them that are modifying resources, and certainly not relying on the eTag for optimistic concurrent updates. This PR as is will be flaky.

Also, the code doesn't currently build, there's a type in a variable name.

2025-01-28 19:27 UTC, amanda-tarafa commented on secretmanager/api/SecretManager.Samples.Tests/DisableRegionalSecretVersionWithEtagTests.cs
> +        Assert.Equal(SecretVersion.Types.State.Disabled, secretVersion.State);
And you are leaving this disabled for other tests to fail.

2025-01-28 19:27 UTC, amanda-tarafa commented on secretmanager/api/SecretManager.Samples.Tests/DestroyRegionalSecretVersionWithEtagTests.cs
> +        SecretName secretName = _fixture.SecretWithVersions.SecretName;
What do you need this for?

2025-01-28 19:27 UTC, amanda-tarafa commented on secretmanager/api/SecretManager.Samples.Tests/DeleteRegionalSecretTests.cs
> +        sss_sample.DeleteRegionalSecret(
Typo, this doesn't build.

2025-02-10 04:41 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/ListRegionalSecretVersionsWithFilterTests.cs
> +    }
I will update the test.

2025-02-10 04:41 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/ListRegionalSecretsTests.cs
> +    }
I will update the test file.

2025-02-10 04:41 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/ListRegionalSecretsWithFilterTests.cs
> +    }
I will update the test file.

2025-02-11 06:46 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples/UpdateRegionalSecret.cs
> +    )
Thanks for catching that! It looks like the lint and formatting tool automatically made these changes.  I'll investigate further and adjust the code to ensure everything passes both the formatting checks and the functional tests. I'll update the PR accordingly.

2025-02-11 07:00 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/RegionalSecretManagerFixture.cs
> +        SecretManagerServiceClient client = new SecretManagerServiceClientBuilder
Have accomodated this change, thanks for pointint it out.

2025-02-11 07:00 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/DeleteRegionalSecretTests.cs
> +        sss_sample.DeleteRegionalSecret(
Have fixed this typo.

2025-02-12 09:34 UTC, YashSaraf11 commented
> Please rebase this PR on main as at the moment your branch is outdated and this PR is including unrelated Secret Manager changes.
> 
> There are several comments that although left in one or two files only, should be addressed everywhere.
> 
> I aslo have some concerns about:
> 
> * assumptions that tests run in a given order
> * assumptions that tests do not run in parallel
> * reuse of fxiture resources in tests that modify said resources
> 
> All of these may be addressed by creating specific resources for each of the tests that modify the resources. And ideally those should be set up and deleted on each of the tests using the fixture methods as helpers. Shares resources in the fixture should only be used for tests that do not modify those resources. I know some of this was inspired by the existing global samples, but, although those are not perfect, there are way less of them that are modifying resources, and certainly not relying on the eTag for optimistic concurrent updates. This PR as is will be flaky.
> 
> Also, the code doesn't currently build, there's a type in a variable name.

Have made the changes in the file as per the suggestion, thanks for pointing it out.

2025-02-12 09:35 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/DisableRegionalSecretVersionWithEtagTests.cs
> +        Assert.Equal(SecretVersion.Types.State.Disabled, secretVersion.State);
Have created a different secret in the specific test file and also disposes of the created resource in the same test file to prevent the test suite to get flaky.

2025-02-12 09:35 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/DestroyRegionalSecretVersionWithEtagTests.cs
> +        SecretName secretName = _fixture.SecretWithVersions.SecretName;
Have created a different secret in the specific test file and also disposes of the created resource in the same test file to prevent the test suite to get flaky.

2025-02-12 09:35 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/EnableRegionalSecretVersionWithEtagTests.cs
> +        SecretVersion disabledSecretVersion = client.DisableSecretVersion(secretVersionName);
Have created a different secret in the specific test file and also disposes of the created resource in the same test file to prevent the test suite to get flaky.

2025-02-12 09:37 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/ListRegionalSecretsWithFilterTests.cs
> +        Console.SetOut(stringWriter);
Have fixed this and used different assert statements to verify the working instead of redirecting the output.

2025-02-12 09:38 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples/IamRegionalRevokeAccess.cs
> +        // Remove the user to the list of bindings.
Have accomodated this change, thanks.

2025-02-12 09:39 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/IamRegionalRevokeAccessTests.cs
> +        SecretName secretName = _fixture.SecretToCreateName;
Understood, thanks for pointing out the flakiness that was existing in the test suite, have fixed all the occurences by creating test specific resources and have deleted/disposed the secrets/resources created in the same test file.

2025-02-12 09:46 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/IamRegionalRevokeAccessTests.cs
> +        Assert.DoesNotContain(result.Bindings,
Have first added the policy to make sure the binding is there and then revoked the access to make it robust.

2025-02-12 09:47 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/IamRegionalGrantAccessTests.cs
> +        SecretName secretName = _fixture.SecretToCreateName;
Here we are granting the access, so this test verifies that post the call the binding contains the required roles and members.

2025-02-12 09:48 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples/EnableRegionalSecretVersionWithEtag.cs
> +            ),
This is being automatically reformatted whenever `dotnet format` is run, if I manually change then certain times the checks fails whenever the PR is updated.

2025-02-12 09:50 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/IamRegionalRevokeAccessTests.cs
> +          projectId: secretName.ProjectId, locationId: secretName.LocationId, secretId: secretName.SecretId,
This is auto formatted by `dotnet format`.

2025-02-13 05:47 UTC, vipul7499 submitted a review, later dismissed

2025-02-18 22:55 UTC, amanda-tarafa requested changes
@YashSaraf11 Can you rebase this PR on main? It now has accumulated changes for other products with changes in over 160 files, and it's very hard to review. Thanks!

2025-02-20 13:48 UTC, YashSaraf11 commented
> @YashSaraf11 Can you rebase this PR on main? It now has accumulated changes for other products with changes in over 160 files, and it's very hard to review. Thanks!

Have rebased this PR on main. Sorry for the inconvenience.

2025-02-21 19:50 UTC, amanda-tarafa requested changes
This is looking good in terms of possible flakiness because of resource sharing across tests. I think there a couple of tests that still need updating, I've called those out. Thanks!

There are a couple other comments for sample code simplification.

And there are the style comments, about the new-line parenthesis and indents. Those are off. I replied to your comment about `dotnet format`. We should fix these at least in sample code, it happens in some tests as well, because it's really an unfamiliar style.

2025-02-21 19:50 UTC, amanda-tarafa commented on secretmanager/api/SecretManager.Samples/EnableRegionalSecretVersionWithEtag.cs
> +            ),
I'm not sure what's doing that. What IDE are you using and are you sure you don't have default style settings that are more suited for a different language? The .editorconfig at the root of this repo [should be respected](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-format) by `dotnet format` and that definetely wouldn't bring parenthesis to the next line. There are other styling issues around indents etc. that I have flagged in several of the files that do not match what's defined in `.editorconfig` (4 space indents).

And I'm not sure what checks would fail, we certainly don't have any style checks on PR presubmits.

2025-02-21 19:50 UTC, amanda-tarafa commented on secretmanager/api/SecretManager.Samples.Tests/CreateRegionalSecretTests.cs
> +        SecretName secretName = _fixture.SecretToCreateName;
Why do you need a SecretToCreateName here? Can't you just create a secret with a random ID? This makes it look like this secret will be used somewhere else, but that's really not possible because we can't rely on tests executing in any given order.

2025-02-21 19:50 UTC, amanda-tarafa commented on secretmanager/api/SecretManager.Samples.Tests/EditRegionalSecretAnnotationsTests.cs
> +        SecretName secretName = _fixture.Secret.SecretName;
Just double checking that adding new annotations to this shared secret won't make other tests fail.

2025-02-21 19:50 UTC, amanda-tarafa commented on secretmanager/api/SecretManager.Samples.Tests/IamRegionalGrantAccessTests.cs
> +        SecretName secretName = _fixture.SecretToCreateName;
This test will fail if the create secret test happens to run after and not before. We cannot rely on the order in which tests run. Here you need to create a secret specific for this test and delete it at the end, similar to what you have done elsewhere.

2025-02-21 19:50 UTC, amanda-tarafa commented on secretmanager/api/SecretManager.Samples.Tests/IamRegionalRevokeAccessTests.cs
> +        SecretName secretName = _fixture.SecretToCreateName;
I think you forgot to change this one.

2025-02-21 19:50 UTC, amanda-tarafa commented on secretmanager/api/SecretManager.Samples.Tests/UpdateRegionalSecretWithAliasTests.cs
> +        SecretName secretName = _fixture.Secret.SecretName;
Double checking here that modifying the shared secret won't make other tests fail.

2025-03-03 08:43 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/IamRegionalGrantAccessTests.cs
> +        SecretName secretName = _fixture.SecretToCreateName;
Sure, I will create separate secret for these tests as well.

2025-03-03 08:44 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/EditRegionalSecretAnnotationsTests.cs
> +        SecretName secretName = _fixture.Secret.SecretName;
No, annotation wouldn't affect other tests that the secret is handling.

2025-03-03 08:44 UTC, YashSaraf11 commented on secretmanager/api/SecretManager.Samples.Tests/CreateRegionalSecretTests.cs
> +        SecretName secretName = _fixture.SecretToCreateName;
I will create the secret here separetly as mentioned for tests.

2025-03-11 14:19 UTC, YashSaraf11 commented
@amanda-tarafa 
Thanks for the detailed review! I've incorporated your feedback and fixed the dotnet format issues.
I also looked into the secret updates. As you mentioned, they're updating different pieces and don't affect the tests.

I believe I've addressed all your points, but please let me know if anything else comes up.

2025-03-11 14:30 UTC, YashSaraf11 reviewed
@amanda-tarafa 
Thanks for the detailed review! I've incorporated your feedback and fixed the dotnet format issues.
I also looked into the secret updates. As you mentioned, they're updating different pieces and don't affect the tests.

I believe I've addressed all your points, but please let me know if anything else comes up.

2025-03-13 06:34 UTC, amanda-tarafa requested changes
There's still one of the secret names that is shared when it shouldn't. I've flagged it.

Also, style is still off in some tests. What IDE are you using?

2025-03-13 06:34 UTC, amanda-tarafa commented on secretmanager/api/SecretManager.Samples.Tests/CreateRegionalSecretTests.cs
> +        SecretName secretName = _fixture.SecretToCreateName;
I think you forgot to push a commit. This is not done yet. Also, once you've changed this, it's likely that you can delete SecretToCreateName from the fixture.

2025-03-13 09:41 UTC, YashSaraf11 commented
> There's still one of the secret names that is shared when it shouldn't. I've flagged it.
> 
> Also, style is still off in some tests. What IDE are you using?

@amanda-tarafa I will update it, can you mention if the style can be due to different dotnet version being used?

2025-03-17 23:45 UTC, amanda-tarafa approved these changes
Thanks for all the fixes!

2025-03-17 23:46 UTC, merged